[versions]
reakt = "0.1.20"
color = "0.0.50"
foundation = "1.4.0"

[libraries]
color-core = { module = "tz.co.asoft:color-core", version.ref = "color" }
color-css = { module = "tz.co.asoft:color-css", version.ref = "color" }
expect-core = { module = "tz.co.asoft:expect-core", version.ref = "foundation" }
kotlinx-browser = { module = "tz.co.asoft:kotlinx-browser", version.ref = "foundation" }

[plugins]
library = { id = "tz.co.asoft.library", version.ref = "foundation" }
