[versions]
react = "17.0.2-pre.265-kotlin-1.5.31"
react_router_dom = "5.3.0-pre.265-kotlin-1.5.31"
extension = "1.0.1-pre.265-kotlin-1.5.31"
css = { strictly = "1.0.0-pre.240-kotlin-1.5.30" } # "1.0.0-pre.265-kotlin-1.5.31"
styled = "5.3.3-pre.265-kotlin-1.5.31"


[libraries]
react-core = { module = "org.jetbrains.kotlin-wrappers:kotlin-react", version.ref = "react" }
react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "react" }
react-router-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom", version.ref = "react_router_dom" }
styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled", version.ref = "styled" }
extension = { module = "org.jetbrains.kotlin-wrappers:kotlin-extensions", version.ref = "extension" }
css = { module = "org.jetbrains.kotlin-wrappers:kotlin-css", version.ref = "css" }